### ISSUE TITLE
Does not work on Windows

### ISSUE THREAD

**Issue by eberkund** [pion/mdns#118]
### What happened?

I am using Windows (11) and running the example programs does not work. I start the server and run `dns-sd -q my-domain.local` from another computer (macOS) and expect to receive a response from the Windows machine running the pion mDNS server. But I don't get anything. I see the mDNS packets coming through in Wireshark but the Go program does not seem to get them and therefore does not respond.

**Comment by bendahl** [comment]
Hi @eberkund,

are you still experiencing this issue? If so, have you tried doing this the other way around? I'm asking, because I'd like to understand whether this is solely a Windows issue or whether something else in your setup might be causing these issues. If it is solely a Windows issue, it might be worth double checking the interface bindings of the server. To my knowledge, the pion/mdns server tries to bind to all available network interfaces - see: https://github.com/pion/mdns/blob/04d95eb6db2ae497c22f08cee9e1f0ac63ec9269/conn.go#L60-L65

I currently cannot test on Windows, so I cannot confirm this. However, using two Linux machines works.

Let me know how it goes.

Cheers
Ben

@Sean-Der: Maybe this is related to #93?

**Comment by edaniels** [comment]
I think this was fixed in https://github.com/pion/mdns/commit/bde59ba7419409133f31f611677c24ea6bc36f22

**Comment by eberkund** [comment]
@edaniels, the latest version fixes it. Thanks.

**Comment by edaniels** [comment]
Great! Thanks for testing :)

**Comment by eberkund** [comment]
@edaniels I am seeing a regression after updating to v2

**Comment by edaniels** [comment]
Ah, sorry! Can you describe the regression so I can look into it? We need windows testing

**Comment by eberkund** [comment]
> Ah, sorry! Can you describe the regression so I can look into it? We need windows testing

I did a basic investigation with WireShark and the client seems to be working fine. I can see the mDNS queries but the server does not respond back.

Reverting back to 1.x fixed the issue.

**Comment by edaniels** [comment]
Gotcha, I likely broke something, sorry! I'll try to test this in the coming days.

**Comment by edaniels** [comment]
Annoying that it auto closed. @eberkund can you check on v2.0.7?

**Comment by eberkund** [comment]
It works on 2.0.7, thanks!
